# Study Guide

In [1]:
from scipy import stats
mult = stats.multinomial(100, [1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
num_samples = 2
print('Generating', num_samples, 'samples:')
samples = mult.rvs(size=num_samples)
print(samples)
print('Value of probability mass function at samples:')
print(mult.pmf(samples))

Generating 2 samples:
[[17 15 19 18 16 15]
 [24 15 14 17 16 14]]
Value of probability mass function at samples:
[1.44130417e-05 3.11292403e-06]


The Dirichlet distribution is a conjugate prior for the multinomial likelihood. The support of
the Dirichlet distribution is all length k probability vectors. This space is also known as the
(k − 1) dimensional simplex. The parameter of the Dirichlet distribution α is a dimensional vector. This vector does
→
k
not have to sum to 1.

In [2]:
from scipy import stats
dirichlet = stats.dirichlet([1, 2, 3, 4])
num_samples = 5
print('Generating', num_samples, 'samples:')
samples = dirichlet.rvs(size=num_samples)
print(samples)
print('Sum of each sample (should be 1):')
print(samples.sum(axis=1))
print('Value of probability density function at each sample:')
print(dirichlet.pdf(samples.transpose()))

Generating 5 samples:
[[0.00594079 0.21020544 0.48046287 0.3033909 ]
 [0.05065745 0.24243819 0.09714126 0.6097631 ]
 [0.21683616 0.19969412 0.32653094 0.25693879]
 [0.04284413 0.1251106  0.09912963 0.73291564]
 [0.05577849 0.29058969 0.20150915 0.45212267]]
Sum of each sample (should be 1):
[1. 1. 1. 1. 1.]
Value of probability density function at each sample:
[40.97821631 15.68460869 10.92156203 14.63675559 32.97770255]


# Pre-class work

In [81]:
import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/cscheffler/482412b75d7b7c8ab83dd86e81d71403/raw/9ed65a9d2bb8455e4b225400f57f2d77f851aec9/socialmobility.csv")
df

father           son  count
0           farm          farm    703
1           farm     unskilled   1478
2           farm       skilled   1430
3           farm  professional   1109
4      unskilled          farm     58
5      unskilled     unskilled   1756
6      unskilled       skilled   1630
7      unskilled  professional   1568
8        skilled          farm     63
9        skilled     unskilled   1453
10       skilled       skilled   2068
11       skilled  professional   2483
12  professional          farm     61
13  professional     unskilled    749
14  professional       skilled   1183
15  professional  professional   3315

In [82]:
import numpy as np

samples = 1000000

postdist_unskilleddad = stats.dirichlet(np.array(df.iloc[:,2][df.iloc[:,0] == 'unskilled']) + 1)
x = postdist_unskilleddad.rvs(size = samples)
print("farm: %f unskilled %f skilled %f professional %f" % tuple(np.array(np.mean(x, axis = 0))))
print("Confidence interval of unskilled is :", np.percentile(x, 2.5, axis = 0)[1], np.percentile(x, 97.5, axis = 0)[1])

farm: 0.011761 unskilled 0.350276 skilled 0.325158 professional 0.312805
Confidence interval of unskilled is : 0.33715414795532683 0.3635311905052255


In [83]:
postdist_professionalson = stats.dirichlet(np.array(df.iloc[:,2][df.iloc[:,1] == 'professional']) + 1)
y = postdist_professionalson.rvs(size = samples)
print("farm: %f unskilled %f skilled %f professional %f" % tuple(np.array(np.mean(y, axis = 0))))
print("Confidence interval of farm is :", np.percentile(y, 2.5, axis = 0)[0], np.percentile(y, 97.5, axis = 0)[0])

farm: 0.130911 unskilled 0.185048 skilled 0.292956 professional 0.391085
Confidence interval of farm is : 0.12380003479069218 0.1381840783509839
